# Generated by Django 4.0.1 on 2022-07-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_photo', models.FileField(blank=True, null=True, upload_to='images/')),
                ('name_of_student', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_registration', models.DateTimeField()),
                ('sr_no', models.CharField(blank=True, max_length=50, null=True)),
                ('class_admission', models.CharField(choices=[('---', '---'), ('nursery', 'NURSERY'), ('lkg', 'LKG'), ('ukg', 'UKG'), ('first', 'FIRST'), ('second', 'SECOND'), ('third', 'THIRD'), ('fourth', 'FOURTH'), ('fifth', 'FIFTH'), ('sixth', 'SIXTH'), ('seventh', 'SEVENTH'), ('eighth', 'EIGHTH')], default='---', max_length=20)),
                ('date_of_birth', models.DateTimeField()),
                ('religion', models.CharField(choices=[('---', '---'), ('hinduism', 'HINDUISM'), ('islam', 'ISLAM'), ('budhism', 'BUDHISM'), ('sikhism', 'SIKHISM'), ('jainism', 'JAINISM')], default='---', max_length=20)),
                ('caste', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, default='INDIAN', max_length=50, null=True)),
                ('gender', models.CharField(choices=[('---', '---'), ('male', 'MALE'), ('female', 'FEMALE'), ('others', 'OTHERS')], default='---', max_length=20)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('student_aadhar_front', models.FileField(blank=True, null=True, upload_to='images/')),
                ('student_aadhar_back', models.FileField(blank=True, null=True, upload_to='images/')),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('father_qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('father_occupation', models.CharField(choices=[('---', '---'), ('business', 'BUSINESS'), ('service', 'SERVICE'), ('farming', 'FARMING'), ('labour', 'LABOUR'), ('others', 'OTHERS')], default='---', max_length=20)),
                ('father_mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('father_address', models.CharField(blank=True, max_length=50, null=True)),
                ('father_aadhar_front', models.FileField(blank=True, null=True, upload_to='images/')),
                ('father_aadhar_back', models.FileField(blank=True, null=True, upload_to='images/')),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_address', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_aadhar_front', models.FileField(blank=True, null=True, upload_to='images/')),
                ('mother_aadhar_back', models.FileField(blank=True, null=True, upload_to='images/')),
                ('medical_issue', models.CharField(blank=True, max_length=100, null=True)),
                ('last_class', models.CharField(choices=[('---', '---'), ('nursery', 'NURSERY'), ('lkg', 'LKG'), ('ukg', 'UKG'), ('first', 'FIRST'), ('second', 'SECOND'), ('third', 'THIRD'), ('fourth', 'FOURTH'), ('fifth', 'FIFTH'), ('sixth', 'SIXTH'), ('seventh', 'SEVENTH'), ('eighth', 'EIGHTH')], default='---', max_length=20)),
                ('form_filled_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_attended_school', models.CharField(blank=True, max_length=100, null=True)),
                ('session', models.IntegerField(choices=[(2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, max_length=4, verbose_name='year')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True)),
                ('disability', models.CharField(choices=[('---', '---'), ('yes', 'YES'), ('no', 'NO')], default='---', max_length=20)),
                ('category', models.CharField(choices=[('---', '---'), ('general', 'GENERAL'), ('obc', 'OBC'), ('sc', 'SC')], default='---', max_length=20)),
                ('father_photo', models.FileField(blank=True, null=True, upload_to='images/')),
                ('mother_photo', models.FileField(blank=True, null=True, upload_to='images/')),
                ('any_sibling', models.CharField(blank=True, default='No', max_length=100, null=True)),
                ('sealed_admission_doc', models.FileField(blank=True, null=True, upload_to='admissionforms/')),
                ('school_last_attended_with_result', models.CharField(blank=True, max_length=100, null=True)),
                ('subjects_studied', models.CharField(blank=True, max_length=100, null=True)),
                ('qualified_for_promotion', models.CharField(blank=True, max_length=100, null=True)),
                ('months_school_dues_paid', models.CharField(blank=True, max_length=100, null=True)),
                ('total_working_days', models.CharField(blank=True, max_length=100, null=True)),
                ('total_days_present', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_curricular_activity', models.CharField(blank=True, max_length=100, null=True)),
                ('character_of_student', models.CharField(blank=True, max_length=100, null=True)),
                ('general_conduct', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_application_of_tc', models.CharField(blank=True, max_length=100, null=True)),
                ('reason_of_leaving', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_issuance_tc', models.CharField(blank=True, max_length=100, null=True)),
                ('tc_prepared_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_file', models.FileField(upload_to='assignment/')),
                ('assignment_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_posting', models.DateTimeField()),
                ('assignment_class', models.CharField(choices=[('---', '---'), ('nursery', 'NURSERY'), ('lkg', 'LKG'), ('ukg', 'UKG'), ('first', 'FIRST'), ('second', 'SECOND'), ('third', 'THIRD'), ('fourth', 'FOURTH'), ('fifth', 'FIFTH'), ('sixth', 'SIXTH'), ('seventh', 'SEVENTH'), ('eighth', 'EIGHTH')], default='---', max_length=20)),
                ('assignment_subject', models.CharField(choices=[('---', '---'), ('english', 'ENGLISH'), ('hindi', 'HINDI'), ('maths', 'MATHS'), ('social science', 'SOCIAL SCIENCE'), ('science', 'SCIENCE'), ('general knowledge', 'GENERAL KNOWLEDGE'), ('hindi grammar', 'HINDI GRAMMAR'), ('english grammar', 'ENGLISH GRAMMAR'), ('drawing', 'DRAWING')], default='---', max_length=40)),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_file', models.FileField(upload_to='gallery/')),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_desc', models.CharField(blank=True, max_length=500, null=True)),
                ('notice_file', models.FileField(upload_to='notices/')),
                ('date_of_posting', models.DateTimeField()),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
